name: Build

on:
  workflow_dispatch:

jobs:
  update-redirect:
    runs-on: ubuntu-22.04
    steps:
      - name: Extract secrets from Keeper
        uses: Keeper-Security/ksm-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
            ${{ vars.KEEPER_BOS_REDIRECT_RECORD_ID }}/field/login > env:BOS_REDIRECT_USER
            ${{ vars.KEEPER_BOS_REDIRECT_RECORD_ID }}/field/password > env:BOS_REDIRECT_PSW
  
      - name: Update BOS redirect table (community)
        env:
          REDIRECT_ID: ${{ vars.BOS_REDIRECT_ADMIN_APP_ID }}
          BOS_REDIRECT_URL: https://redirect.bonitasoft.com/
          BOS_RELEASE_ASSET_URL: https"%"3A"%"2F"%"2Fgithub.com%"2Fbonitasoft%"2Fbonita-admin-application%"2Freleases%"2Fdownload%"2F9.0.8%"2Fbonita-admin-application-9.0.8.bos
        run: | 
          MAINTENANCE_VERSION="$(cut -d '.' -f3 <<< 9.0.8)"
          MAJOR_VERSION="$(cut -d '.' -f1,2 <<< 9.0.8)"
          STATUS_CODE=$(curl -s -o /dev/null -L -w "%{http_code}\\n" "$BOS_REDIRECT_URL" -u "$BOS_REDIRECT_USER:$BOS_REDIRECT_PSW" -H "Content-Type: application/x-www-form-urlencoded" --data "id=$REDIRECT_ID&product=bos&major_version=$MAJOR_VERSION&minor_version=$MAINTENANCE_VERSION&URL=$BOS_RELEASE_ASSET_URL&description=Bonita+Admin+App&submit=true")
          if [ $STATUS_CODE!="200" ] 
          then
              echo $STATUS_CODE
              echo "Redirect entry for tuple ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) already exists. Performing update..."
              STATUS_CODE=$(curl -s -o /dev/null -L -w "%{http_code}\\n" "$BOS_REDIRECT_URL" -u "$BOS_REDIRECT_USER:$BOS_REDIRECT_PSW" -H "Content-Type: application/x-www-form-urlencoded" --data "action=modify&id=$REDIRECT_ID&product=bos&major_version=$MAJOR_VERSION&minor_version=$MAINTENANCE_VERSION&URL=$BOS_RELEASE_ASSET_URL&description=Bonita+Admin+App&submit_modify=true")
              if [ $STATUS_CODE!="200" ] 
              then
                echo $STATUS_CODE
                echo "Failed to update BOS redirect entry ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) with new URL: $BOS_RELEASE_ASSET_URL"
              else
                echo "BOS Redirect entry ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) updated with URL: $BOS_RELEASE_ASSET_URL"
              fi   
          else
              echo "BOS Redirect entry ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) created with URL: $BOS_RELEASE_ASSET_URL"
          fi